### PR TITLE
Require at least PSA 0.2.20

### PR DESCRIPTION
**Pull request by rlucioni**
0.2.20 includes an index on the Association model.

@clintonb @jibsheet @adampalay

### CODE REVIEW

**Comment by rlucioni** [comment]
https://github.com/omab/python-social-auth/pull/969

**Comment by jibsheet** [comment]
:+1:

**Comment by clintonb** [comment]
👍

**Comment by clintonb** [comment]
Unless there is more to release, you can save time and update the package version, too.

**Comment by rlucioni** [comment]
Nice catch @clintonb, thanks. Updated.

**Pull request merged**
